### ISSUE TITLE
TODO: verification ideas

### ISSUE THREAD

**Issue by donkim1212** [donkim1212/nbc-websocket-game-server#7]
## 관련 Issue

없음

---

## 할 일

- [ ] ~~Socket.js (클라)에서 job queue로 'response' 로 받은 data 담아두고 index.js에서 poll하여 처리하기~~
- [ ] 스테이지 이동 요청 시 획득한 아이템 목록을 같이 보내서 검증?
- [ ] 스테이지 이동 시 서버에서 아이템 스폰 시간을 담은 배열을 같이 전송?
- [ ] 아이템 출몰 순서를 정하는 random-seed를 지정하고, 스테이지 이동 시 클라이언트에서 발생한 아이템 spawn 의 itemId와 timestamp 로그를 함께 전송하여 검증할 수 있도록 변경해보기

---

## 비고

-
